name: Terraform Validate

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        directory:
          - aws/ec2/cpu-stress
          - azure/vm/shutdown

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.6"

      - name: Terraform format
        working-directory: ${{ matrix.directory }}
        run: terraform fmt -check -recursive

      - name: Terraform init
        working-directory: ${{ matrix.directory }}
        run: terraform init -backend=false

      - name: Terraform validate
        working-directory: ${{ matrix.directory }}
        run: terraform validate
